<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DestinationSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('destinations')->insert([
            [
                'name' => 'Machu Picchu',
                'country' => 'Peru',
                'region' => 'South America',
                'cost_level' => 'Moderate',
                'activities' => json_encode(['Hiking & Trekking', 'Cultural Tours', 'Photography', 'Historical Sightseeing']),
                'average_daily_budget' => 150,
                'annual_visitors' => 1500000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Santorini',
                'country' => 'Greece',
                'region' => 'Europe',
                'cost_level' => 'Premium',
                'activities' => json_encode(['Beach & Relaxation', 'Food & Wine Tasting', 'Photography', 'Sailing & Boating']),
                'average_daily_budget' => 250,
                'annual_visitors' => 2000000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kyoto',
                'country' => 'Japan',
                'region' => 'Asia',
                'cost_level' => 'Moderate',
                'activities' => json_encode(['Cultural Tours', 'Historical Sightseeing', 'Food & Wine Tasting', 'Photography']),
                'average_daily_budget' => 180,
                'annual_visitors' => 5300000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Serengeti National Park',
                'country' => 'Tanzania',
                'region' => 'Africa',
                'cost_level' => 'Premium',
                'activities' => json_encode(['Wildlife Safari', 'Photography', 'Hot Air Ballooning', 'Camping']),
                'average_daily_budget' => 300,
                'annual_visitors' => 350000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Queenstown',
                'country' => 'New Zealand',
                'region' => 'Oceania',
                'cost_level' => 'Premium',
                'activities' => json_encode(['Adventure Sports', 'Skiing & Snowboarding', 'Hiking & Trekking', 'Paragliding']),
                'average_daily_budget' => 200,
                'annual_visitors' => 3000000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Reykjavik',
                'country' => 'Iceland',
                'region' => 'Europe',
                'cost_level' => 'Premium',
                'activities' => json_encode(['Hiking & Trekking', 'Hot Air Ballooning', 'Photography', 'Volcano Tours']),
                'average_daily_budget' => 280,
                'annual_visitors' => 2300000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Cusco',
                'country' => 'Peru',
                'region' => 'South America',
                'cost_level' => 'Budget',
                'activities' => json_encode(['Hiking & Trekking', 'Cultural Tours', 'Historical Sightseeing', 'Food & Wine Tasting']),
                'average_daily_budget' => 60,
                'annual_visitors' => 2700000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bali',
                'country' => 'Indonesia',
                'region' => 'Asia',
                'cost_level' => 'Budget',
                'activities' => json_encode(['Beach & Relaxation', 'Surfing', 'Yoga & Wellness Retreats', 'Cultural Tours']),
                'average_daily_budget' => 70,
                'annual_visitors' => 6200000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Banff National Park',
                'country' => 'Canada',
                'region' => 'North America',
                'cost_level' => 'Moderate',
                'activities' => json_encode(['Hiking & Trekking', 'Skiing & Snowboarding', 'Kayaking & Canoeing', 'Wildlife Safari']),
                'average_daily_budget' => 180,
                'annual_visitors' => 4000000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Patagonia',
                'country' => 'Argentina',
                'region' => 'South America',
                'cost_level' => 'Premium',
                'activities' => json_encode(['Hiking & Trekking', 'Rock Climbing', 'Photography', 'Camping']),
                'average_daily_budget' => 220,
                'annual_visitors' => 400000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Marrakech',
                'country' => 'Morocco',
                'region' => 'Africa',
                'cost_level' => 'Budget',
                'activities' => json_encode(['Cultural Tours', 'Food & Wine Tasting', 'Historical Sightseeing', 'Nightlife & Entertainment']),
                'average_daily_budget' => 55,
                'annual_visitors' => 3000000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dubrovnik',
                'country' => 'Croatia',
                'region' => 'Europe',
                'cost_level' => 'Moderate',
                'activities' => json_encode(['Historical Sightseeing', 'Beach & Relaxation', 'Kayaking & Canoeing', 'Food & Wine Tasting']),
                'average_daily_budget' => 160,
                'annual_visitors' => 1400000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Cancun',
                'country' => 'Mexico',
                'region' => 'North America',
                'cost_level' => 'Moderate',
                'activities' => json_encode(['Beach & Relaxation', 'Scuba Diving & Snorkeling', 'Nightlife & Entertainment', 'Cultural Tours']),
                'average_daily_budget' => 140,
                'annual_visitors' => 8000000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Phuket',
                'country' => 'Thailand',
                'region' => 'Asia',
                'cost_level' => 'Budget',
                'activities' => json_encode(['Beach & Relaxation', 'Scuba Diving & Snorkeling', 'Food & Wine Tasting', 'Nightlife & Entertainment']),
                'average_daily_budget' => 80,
                'annual_visitors' => 9500000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Swiss Alps',
                'country' => 'Switzerland',
                'region' => 'Europe',
                'cost_level' => 'Luxury',
                'activities' => json_encode(['Skiing & Snowboarding', 'Hiking & Trekking', 'Rock Climbing', 'Photography']),
                'average_daily_budget' => 400,
                'annual_visitors' => 1200000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
